### PR TITLE
Update default nodeSelector to help with helm 3 compatibility

### PR DESCRIPTION
**Pull request by jessebye**
Helm 3 has [a bug](https://github.com/helm/helm/issues/5184) that prevents null overrides from working correctly. That makes it impossible to properly remove the `nodeSelector` from the daemonset and deploy the agent to all nodes.

By adjusting the default to deploy to all nodes, then we can work around this bug until it is fixed.

### CODE REVIEW

**Comment by olhado** [comment]
@jessebye Thanks for the contribution! I did not know about that bug.

Some context on the original settings: We went back and forth on defaulting to all or not. Our concern was that users could accidentally send the agent everywhere when they meant to just put it on a subset to test it out, simply by running `helm install threatstack/threatstack-agent`. Not a great customer/prospect experience.

That said, I'm going to talk internally to make sure they are okay with the change though, since we don't want to put anyone into a dead-end deployment.

**Comment by olhado** [comment]
Hey @jessebye we need to update documentation for people who pull the helm chart package from our official repository, but the plan is to accept your changes soon after that is ready.

Thanks again for the contribution!

**Comment by jessebye** [comment]
@olhado just to confirm, do you need anything further from me on this branch? Or will this be handled on your end?

**Comment by olhado** [comment]
This is all on our end. Thanks again!

**Comment by jessebye** [comment]
@olhado any luck pushing this through? We are blocked from deploying the TS agent until this is fixed...

**Comment by olhado** [comment]
Hey @jessebye, sorry for the delay, I'm merging this in now.

**Comment by jessebye** [comment]
Thanks @olhado! One issue, it looks like this chart didn't get published? I am unable to install 1.0.3 in our cluster.

**Comment by olhado** [comment]
Hi Jesse,

The build of the package will be next week. If you like (and are allowed), you can also build the package yourself. Sorry for the delays.

----- Original message -----

**Comment by olhado** [comment]
@jessebye The 1.0.3 package with your fix should be available. Thanks again for the fix!

**Pull request merged**
